"""Contract tests for the learn-namespace ownership gate."""
from __future__ import annotations

import importlib.util
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))
SPEC = importlib.util.spec_from_file_location(
    "check_learn_namespace",
    SCRIPTS / "check-learn-namespace.py",
)
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)

GENERATED = (
    "# Learn — demo\n\n"
    "> Generated by `scripts/export_learn_to_obsidian.py`. "
    "Do not edit by hand — changes are overwritten on the next export.\n"
)
AUTHORED = "---\ntype: learn\nstatus: verified\n---\n\n# A lesson someone wrote\n"


def build_vault(root: Path) -> Path:
    learn = root / "memory" / "learn"
    for name in ("patterns", "repos", "tags"):
        (learn / name).mkdir(parents=True)
    (learn / "index.md").write_text(GENERATED, encoding="utf-8")
    (learn / "repos" / "demo.md").write_text(GENERATED, encoding="utf-8")
    (learn / "patterns" / "learn_1.md").write_text(GENERATED, encoding="utf-8")
    (learn / "tags" / "demo.md").write_text(GENERATED, encoding="utf-8")
    return learn


class LearnNamespaceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp)
        self.learn = build_vault(self.tmp)

    def test_all_generated_namespace_passes(self) -> None:
        self.assertEqual(MODULE.authored_files_in_owned_namespace(self.tmp), [])

    def test_authored_note_in_repos_is_caught(self) -> None:
        """The defect: an authored note force-added into the generated namespace.

        `memory/learn/repos/atlas-core.md` held an 83-line lesson with
        source_evidence_refs until an unrelated export overwrote it with the
        generated index.
        """
        (self.learn / "repos" / "atlas-core.md").write_text(AUTHORED, encoding="utf-8")
        found = MODULE.authored_files_in_owned_namespace(self.tmp)
        self.assertEqual([str(p) for p in found], ["memory/learn/repos/atlas-core.md"])

    def test_authored_note_caught_in_every_owned_directory(self) -> None:
        for name in ("patterns", "repos", "tags"):
            (self.learn / name / "authored.md").write_text(AUTHORED, encoding="utf-8")
        found = {p.parent.name for p in MODULE.authored_files_in_owned_namespace(self.tmp)}
        self.assertEqual(found, {"patterns", "repos", "tags"})

    def test_owned_index_is_checked(self) -> None:
        (self.learn / "index.md").write_text(AUTHORED, encoding="utf-8")
        found = [str(p) for p in MODULE.authored_files_in_owned_namespace(self.tmp)]
        self.assertIn("memory/learn/index.md", found)

    def test_flat_namespace_is_not_checked(self) -> None:
        """Authored notes belong in the flat namespace; the exporter never writes it."""
        (self.learn / "an-authored-lesson.md").write_text(AUTHORED, encoding="utf-8")
        (self.learn / "_stale-pre-marker").mkdir()
        (self.learn / "_stale-pre-marker" / "old.md").write_text(AUTHORED, encoding="utf-8")
        self.assertEqual(MODULE.authored_files_in_owned_namespace(self.tmp), [])

    def test_absent_vault_is_not_a_failure(self) -> None:
        """memory/ is gitignored, so CI has no vault at all."""
        empty = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, empty)
        self.assertEqual(MODULE.authored_files_in_owned_namespace(empty), [])

    def test_real_vault_is_clean(self) -> None:
        self.assertEqual(MODULE.authored_files_in_owned_namespace(ROOT), [])


if __name__ == "__main__":
    unittest.main()
