#!/usr/bin/env python3
"""Render local-only views/top-lists from the pattern library (FAS 6).

Local convenience renderer over local data — NOT mq-agent selection/export, and
deliberately not in mqobsidian/scripts/ (ownership boundary). Reads
`patterns/patterns.jsonl`, writes markdown views into `views/`.

v1 ranking is a transparent STRUCTURAL heuristic, not usage data. Real
usage-backed scores arrive in FAS 8; re-run this then.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
PATTERNS = HERE / "patterns" / "patterns.jsonl"
OBSERVATIONS = HERE / "inbox" / "observations.jsonl"
VIEWS = HERE / "views"
MQLAUNCH = HERE / "mqlaunch"

# Patterns that trace to a logged seed observation (see LIBRARY.md provenance).
OBSERVATION_BACKED = {
    "repo-quick-state",
    "roadmap-locate",
    "open-question-locate",
    "ownership-boundary-check",
    "public-safe-preflight",
}

HEADER = (
    "<!-- GENERATED by memory/commands/build_views.py — do not hand-edit. "
    "Source: patterns/patterns.jsonl + inbox/observations.jsonl. "
    "Ranking = structural prior + usage bonus (see SCORING.md). -->\n\n"
)


def load_jsonl(path: Path) -> list[dict]:
    out: list[dict] = []
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            out.append(json.loads(line))
    return out


def structural_prior(p: dict) -> float:
    """FAS 6 structural floor: provenance > reusability > breadth."""
    score = 0.0
    score += 2.0 if p["id"] in OBSERVATION_BACKED else 0.0
    score += 1.0 if p.get("repo_scope") == "generic" else 0.0
    score += 0.1 * len(p.get("task_tags", []))
    score += 0.001 * len(p.get("use_when", ""))
    return score


def compute_signals(patterns: list[dict], observations: list[dict]) -> None:
    """Attach `_signals` and a combined `_score` to each pattern (see SCORING.md)."""
    by_pattern: dict[str, list[dict]] = {}
    for o in observations:
        pid = o.get("pattern_id")
        if pid:
            by_pattern.setdefault(pid, []).append(o)

    # Raw signals first, then normalize frequency/reuse to the busiest pattern.
    for p in patterns:
        obs = by_pattern.get(p["id"], [])
        n = len(obs)
        worked = sum(1 for o in obs if o.get("outcome") == "worked")
        sessions = {o.get("session_ref") for o in obs if o.get("session_ref")}
        p["_raw"] = {
            "prior": structural_prior(p),
            "frequency": n,
            "success": (worked / n) if n else None,
            "reuse": len(sessions),
            "operator_preference": float(p.get("operator_preference", 0)),
        }

    max_prior = max((p["_raw"]["prior"] for p in patterns), default=0) or 1.0
    max_freq = max((p["_raw"]["frequency"] for p in patterns), default=0) or 1
    max_reuse = max((p["_raw"]["reuse"] for p in patterns), default=0) or 1

    for p in patterns:
        r = p["_raw"]
        prior_n = r["prior"] / max_prior
        freq_n = r["frequency"] / max_freq
        reuse_n = r["reuse"] / max_reuse
        success = r["success"] or 0.0
        combined = (
            prior_n
            + 0.25 * freq_n
            + 0.15 * success
            + 0.10 * reuse_n
            + r["operator_preference"]
            # time_saving and stability: weight 0 in v1 (not measurable yet)
        )
        p["_signals"] = {
            "prior_n": round(prior_n, 3),
            "frequency": r["frequency"],
            "success": round(success, 3) if r["success"] is not None else None,
            "reuse": r["reuse"],
        }
        p["_score"] = round(combined, 3)


def table(rows: list[dict], cols: list[tuple[str, str]]) -> str:
    head = "| " + " | ".join(c for _, c in cols) + " |\n"
    sep = "| " + " | ".join("---" for _ in cols) + " |\n"
    body = ""
    for r in rows:
        body += "| " + " | ".join(str(r.get(k, "")) for k, _ in cols) + " |\n"
    return head + sep + body


def write(name: str, title: str, note: str, content: str) -> None:
    VIEWS.mkdir(exist_ok=True)
    (VIEWS / name).write_text(
        f"{HEADER}# {title}\n\n{note}\n\n{content}", encoding="utf-8"
    )


def main() -> int:
    patterns = load_jsonl(PATTERNS)
    observations = load_jsonl(OBSERVATIONS)
    compute_signals(patterns, observations)
    for p in patterns:
        p["_tags"] = ", ".join(p.get("task_tags", []))
        s = p["_signals"]
        p["_why"] = f"prior {s['prior_n']} · freq {s['frequency']} · success {s['success']} · reuse {s['reuse']}"

    ranked = sorted(patterns, key=lambda p: (-p["_score"], p["id"]))

    # 1. Most reusable (top 10 by combined score)
    write(
        "top-reusable.md",
        "Top reusable patterns",
        "Ranked by combined score = structural prior + usage bonus (frequency, "
        "success, reuse). See SCORING.md; usage is thin at v1 seed.",
        table(ranked[:10], [("id", "Pattern"), ("repo_scope", "Scope"), ("_tags", "Tags"), ("_score", "Score")]),
    )

    # Explainability view: per-pattern signal breakdown
    write(
        "scores.md",
        "Score breakdown",
        "Why each pattern ranks where it does. combined = prior_n + 0.25·freq_n + "
        "0.15·success + 0.10·reuse_n (time_saving/stability weight 0 in v1).",
        table(ranked, [("id", "Pattern"), ("_why", "Signals"), ("_score", "Combined")]),
    )

    # 2. Safest (read-only only — the default-visible tier)
    read_only = [p for p in ranked if p["risk_class"] == "read-only"]
    mutating = [p for p in ranked if p["risk_class"] == "mutating"]
    write(
        "safest.md",
        "Safest patterns",
        f"The {len(read_only)} `read-only` patterns — the default-visible tier. "
        f"The {len(mutating)} `mutating` patterns are listed separately in "
        "`mutating.md` and hidden by default.",
        table(read_only, [("id", "Pattern"), ("risk_class", "Risk"), ("_tags", "Tags"), ("_score", "Score")]),
    )

    # 2b. Mutating patterns (separated, hidden by default — show preconditions)
    write(
        "mutating.md",
        "Mutating patterns (opt-in)",
        f"{len(mutating)} `mutating` patterns. Hidden by default in the consumer; "
        "surface only on explicit opt-in. Always check `preconditions` first.",
        table(mutating, [("id", "Pattern"), ("preconditions", "Preconditions"), ("recovery", "Recovery")]),
    )

    # 3. Best diagnostic patterns
    diag = [p for p in ranked if "diagnose" in p.get("task_tags", [])]
    write(
        "diagnostic.md",
        "Diagnostic patterns",
        "Patterns tagged `diagnose` — for finding the next step or a failure source.",
        table(diag, [("id", "Pattern"), ("use_when", "Use when"), ("_score", "Score")]),
    )

    # 4. Top patterns per repo_scope
    by_repo = ""
    for scope in sorted({p.get("repo_scope", "?") for p in patterns}):
        rows = [p for p in ranked if p.get("repo_scope") == scope]
        by_repo += f"## {scope}\n\n" + table(rows, [("id", "Pattern"), ("_tags", "Tags"), ("_score", "Score")]) + "\n"
    write("by-repo.md", "Patterns per repo scope", "Grouped by `repo_scope`.", by_repo.rstrip() + "\n")

    # 5. Top patterns per task-type (fastest retrieval path)
    all_tags = sorted({t for p in patterns for t in p.get("task_tags", [])})
    by_tag = ""
    for tag in all_tags:
        rows = [p for p in ranked if tag in p.get("task_tags", [])]
        by_tag += f"## {tag}\n\n" + table(rows, [("id", "Pattern"), ("repo_scope", "Scope"), ("_score", "Score")]) + "\n"
    write("by-task-type.md", "Patterns per task type", "Grouped by `task_tags` — the fastest way to find a pattern for a job.", by_tag.rstrip() + "\n")

    emit_mqlaunch_output(ranked, all_tags)

    print(f"rendered 6 views + recommended.json from {len(patterns)} patterns")
    return 0


def emit_mqlaunch_output(ranked: list[dict], all_tags: list[str]) -> None:
    """Emit the small, stable local output mqlaunch consumes (see mqlaunch/CONTRACT.md)."""
    display_keys = (
        "id", "name", "description", "use_when", "avoid_when",
        "command_template", "risk_class", "repo_scope", "task_tags",
        "preconditions", "recovery",
    )
    patterns = []
    for rank, p in enumerate(ranked, 1):
        rec = {k: p[k] for k in display_keys if k in p}
        rec["rank"] = rank
        rec["score"] = p["_score"]
        rec["signals"] = p["_signals"]
        patterns.append(rec)

    def ids_where(pred) -> list[str]:
        return [p["id"] for p in ranked if pred(p)]

    default_visible_risk = ["read-only"]
    visible = lambda p: p["risk_class"] in default_visible_risk

    slices = {
        # default-visible slices exclude mutating; mqlaunch opts in via `mutating`
        "best_next": [p["id"] for p in ranked if visible(p)][:5],
        "safe_first": ids_where(lambda p: p["risk_class"] == "read-only")[:5],
        "best_review": ids_where(lambda p: "review" in p.get("task_tags", [])),
        "best_diagnostics": ids_where(lambda p: "diagnose" in p.get("task_tags", [])),
        "mutating": ids_where(lambda p: p["risk_class"] == "mutating"),
        "by_task": {t: ids_where(lambda p, t=t: t in p.get("task_tags", [])) for t in all_tags},
        "by_repo": {
            s: ids_where(lambda p, s=s: p.get("repo_scope") == s)
            for s in sorted({p.get("repo_scope", "?") for p in ranked})
        },
    }

    output = {
        "schema": "command-recommendations.v1",
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "repo": "mqobsidian",
        "allowed_actions": ["show", "copy"],
        "default_visible_risk": default_visible_risk,
        "patterns": patterns,
        "slices": slices,
    }
    MQLAUNCH.mkdir(exist_ok=True)
    (MQLAUNCH / "recommended.json").write_text(
        json.dumps(output, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    raise SystemExit(main())
