#!/usr/bin/env python3
"""Feedback engine (FAS 10): turn usage + feedback into PROPOSALS.

Reads patterns.jsonl, inbox/observations.jsonl, feedback/feedback.jsonl and
writes feedback/proposals.md. It **proposes** promotions/downgrades/inbox
candidates/cleanup — it NEVER edits the curated store (patterns.jsonl). A human
applies proposals via a manual curation pass. Local-only; not in scripts/
(ownership boundary). See feedback/README.md and CURATION.md.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
PATTERNS = HERE / "patterns" / "patterns.jsonl"
OBSERVATIONS = HERE / "inbox" / "observations.jsonl"
FEEDBACK = HERE / "feedback" / "feedback.jsonl"
PROPOSALS = HERE / "feedback" / "proposals.md"


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def main() -> int:
    patterns = {p["id"]: p for p in load_jsonl(PATTERNS)}
    observations = load_jsonl(OBSERVATIONS)
    feedback = load_jsonl(FEEDBACK)

    # Aggregate usage (observations) and feedback per pattern_id.
    obs_by_pat: dict[str, list[dict]] = defaultdict(list)
    unlinked: list[dict] = []
    for o in observations:
        pid = o.get("pattern_id")
        if pid:
            obs_by_pat[pid].append(o)
        else:
            unlinked.append(o)

    fb_by_pat: dict[str, dict[str, int]] = defaultdict(lambda: {"helped": 0, "not_helped": 0, "uncertain": 0})
    for f in feedback:
        pid = f.get("pattern_id")
        out = f.get("outcome")
        if isinstance(pid, str) and pid in patterns and isinstance(out, str) and out in ("helped", "not_helped", "uncertain"):
            fb_by_pat[pid][out] += 1

    promote, promote_ready, downgrade, cleanup = [], [], [], []
    for pid, p in patterns.items():
        obs = obs_by_pat.get(pid, [])
        worked = sum(1 for o in obs if o.get("outcome") == "worked")
        fb = fb_by_pat.get(pid, {"helped": 0, "not_helped": 0, "uncertain": 0})
        status = p.get("status")
        mutating = p.get("risk_class") != "read-only"

        # value reasons from real usage (CURATION): worked usage and/or positive feedback
        fb_positive = fb["helped"] >= 1 and fb["not_helped"] == 0
        reasons = []
        if worked >= 1:
            reasons.append(f"{worked} worked observation(s)")
        if fb_positive:
            reasons.append(f"{fb['helped']} 'helped', 0 'not_helped'")

        # Policy (CURATION): observations can MINT and RANK a pattern, but promotion
        # to active REQUIRES a confirming feedback record — "looked good 3 times" is a
        # candidate, not proof. Mutating additionally needs worked usage (>=2 signals).
        if status == "experimental":
            if fb_positive and (not mutating or worked >= 1):
                promote.append((pid, "active", "; ".join(reasons)))
            elif worked >= 2:
                # meets the observational bar, but no confirming feedback yet
                promote_ready.append(
                    (pid, "awaiting feedback", f"{worked} worked observation(s); no feedback record yet")
                )

        # Downgrade: repeated not_helped and a losing help-rate.
        denom = fb["helped"] + fb["not_helped"]
        if fb["not_helped"] >= 2 and denom and fb["helped"] / denom < 0.5:
            downgrade.append((pid, "stale (review)", f"{fb['not_helped']} 'not_helped' of {denom} judged"))

        if status == "deprecated":
            cleanup.append((pid, "prune from default views", "status=deprecated"))

    # Inbox candidates: unlinked observations (a 'missing' signal).
    inbox = [
        (o.get("sanitized_command", "?"), o.get("task_type", "?"), o.get("note", ""))
        for o in unlinked
    ]

    def section(title: str, rows: list[tuple], cols: list[str]) -> str:
        out = f"## {title}\n\n"
        if not rows:
            return out + "_None._\n\n"
        out += "| " + " | ".join(cols) + " |\n| " + " | ".join("---" for _ in cols) + " |\n"
        for r in rows:
            out += "| " + " | ".join(str(c) for c in r) + " |\n"
        return out + "\n"

    body = (
        "<!-- GENERATED by memory/commands/feedback.py — proposals only, never applied. "
        "Apply via a manual curation pass on patterns.jsonl. -->\n\n"
        f"# Feedback proposals\n\nGenerated {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} "
        f"from {len(observations)} observations + {len(feedback)} feedback records. "
        "**The loop proposes; a human commits.**\n\n"
        + section("Promote (experimental → active)", promote, ["Pattern", "→", "Why"])
        + section("Promotion-ready (awaiting feedback)", promote_ready, ["Pattern", "State", "Why"])
        + section("Downgrade (review / stale)", downgrade, ["Pattern", "→", "Why"])
        + section("Inbox candidates (unlinked observations = 'missing')", inbox, ["Command", "Task", "Note"])
        + section("Cleanup", cleanup, ["Pattern", "Action", "Why"])
    )
    PROPOSALS.write_text(body, encoding="utf-8")
    print(
        f"proposals: {len(promote)} promote, {len(promote_ready)} promotion-ready, "
        f"{len(downgrade)} downgrade, {len(inbox)} inbox, {len(cleanup)} cleanup "
        "→ feedback/proposals.md"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
