#!/usr/bin/env python3
"""Fail when an authored note sits in the learn export's generated namespace.

`export_learn_to_obsidian.py` owns four paths under `memory/learn/` and
overwrites them on every run:

    patterns/<lesson-id>.md    repos/<repo-slug>.md    tags/<slug>.md    index.md

Two authored notes were force-added into that namespace anyway, to make them
tracked: `repos/atlas-core.md` (an 83-line lesson with `source_evidence_refs`,
mqobsidian #123) and `repos/repo-signal.md`. On 2026-09-30 an export that had
nothing to do with either one overwrote the atlas-core note with its generated
index. Any export touching that repo would have done the same, and nothing
warned: the exporter reports `pattern_files_updated`, and a repo index is not a
pattern file.

The rule is not "generated files must not be tracked" -- this repo tracks
generated artefacts deliberately, from `memory/learn/agent/mqobsidian.md` to
`examples/repo-context-exports/`. The rule is that everything in the owned
namespace must actually be current generator output, so overwriting it is free.
Authored notes belong in the flat `memory/learn/<slug>.md` namespace, which the
exporter never writes.

Two different failures trip this, and they need different remedies:

- an **authored note** placed there, usually to make it tracked -- move it to
  the flat namespace and re-run the export;
- **stale output from an older exporter** whose lesson has left the store --
  the exporter has no deletion pass, so it lingers, orphaned and unlinked. Four
  pattern files and two tag pages from June/July 2026 were found this way. Check
  the id against the lessons store before removing anything: these files are
  untracked, so a delete is unrecoverable.

Local-only by necessity: `memory/` is gitignored, so CI has no vault to check.
It runs from release-check.sh, and `scripts/check-gate-parity.py` declares it
LOCAL_ONLY with that reason.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

LEARN_ROOT = Path("memory") / "learn"

# Directories the exporter writes a file per record into.
OWNED_DIRS = ("patterns", "repos", "tags")

# Single files the exporter owns inside the learn root.
OWNED_FILES = ("index.md",)

# Emitted into every file the exporter writes.
GENERATED_MARKER = "Generated by `scripts/export_learn_to_obsidian.py`"


def authored_files_in_owned_namespace(root: Path = REPO_ROOT) -> list[Path]:
    """Return every file in the owned namespace that is not generator output."""
    learn = root / LEARN_ROOT
    if not learn.is_dir():
        return []

    candidates: list[Path] = []
    for name in OWNED_DIRS:
        directory = learn / name
        if directory.is_dir():
            candidates.extend(sorted(p for p in directory.glob("*.md") if p.is_file()))
    for name in OWNED_FILES:
        path = learn / name
        if path.is_file():
            candidates.append(path)

    offenders = []
    for path in candidates:
        if GENERATED_MARKER not in path.read_text(encoding="utf-8"):
            offenders.append(path.relative_to(root))
    return offenders


def main() -> int:
    learn = REPO_ROOT / LEARN_ROOT
    if not learn.is_dir():
        print("learn namespace check skipped: no local vault at memory/learn")
        return 0

    offenders = authored_files_in_owned_namespace()
    if offenders:
        print(
            "files in the learn export's generated namespace are not current "
            "generator output:",
            file=sys.stderr,
        )
        for path in offenders:
            print(f"  - {path}", file=sys.stderr)
        print(
            "\nThe next export of that repo or tag overwrites these files.\n"
            "  If a file is an authored note: move it to the flat "
            "memory/learn/<slug>.md namespace, which the exporter never writes, "
            "then re-run the export so the generated index owns the path again.\n"
            "  If it is stale output from an older exporter: check its id against "
            "the lessons store first. These files are untracked, so prefer moving "
            "them aside over deleting them.",
            file=sys.stderr,
        )
        return 1

    print("learn namespace checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
