#!/usr/bin/env python3
"""Render local-only views over sanitized workflow-run observations (Phase 9).

Local convenience renderer over local data — NOT mq-agent orchestration, and
deliberately not in mqobsidian/scripts/ (ownership boundary, same as
memory/commands/build_views.py). Reads
`inbox/workflow-observations.jsonl` (records validate against
schemas/workflow-observation.v1.json) and writes markdown views into `views/`.

mqobsidian only *shows* which workflow sequences recur — it never runs them.
Recurrence alone never promotes a sequence (ADR-007, ADR-008): the proposals
view lists candidates only; promotion is decided by the scoring engine, not here.
This module has no execute path and writes nothing under memory/local/.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import cast

HERE = Path(__file__).resolve().parent
OBSERVATIONS = HERE / "inbox" / "workflow-observations.jsonl"
VIEWS = HERE / "views"

# A sequence must recur at least this many times to surface as a reuse proposal.
# A floor only — it never promotes; promotion is the scoring engine's call.
PROPOSAL_MIN_FREQUENCY = 3

HEADER = (
    "<!-- GENERATED by memory/workflows/build_workflow_views.py — do not "
    "hand-edit. Source: inbox/workflow-observations.jsonl. Views are show-only; "
    "mqobsidian cannot run workflows. Recurrence never promotes (ADR-007/008). -->\n\n"
)


def load_jsonl(path: Path) -> list[dict]:
    out: list[dict] = []
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            out.append(json.loads(line))
    return out


def _seq_key(obs: dict) -> str:
    return " → ".join(obs.get("tool_sequence", []))


def aggregate_sequences(observations: list[dict]) -> list[dict]:
    """Group runs by tool_sequence and compute frequency/success/duration/approvals."""
    groups: dict[str, list[dict]] = defaultdict(list)
    for o in observations:
        groups[_seq_key(o)].append(o)

    rows: list[dict] = []
    for seq, runs in groups.items():
        n = len(runs)
        completed = sum(1 for r in runs if r.get("outcome") == "completed")
        durations = [r["duration_ms"] for r in runs if isinstance(r.get("duration_ms"), (int, float))]
        approvals = [r.get("approval_count", 0) for r in runs]
        templates = sorted({r.get("template", "?") for r in runs})
        rows.append({
            "sequence": seq or "(empty)",
            "frequency": n,
            "success": round(completed / n, 3) if n else 0.0,
            "avg_duration_ms": round(sum(durations) / len(durations)) if durations else None,
            "avg_approvals": round(sum(approvals) / n, 2) if n else 0.0,
            "templates": ", ".join(templates),
        })
    rows.sort(key=lambda r: (-r["frequency"], -r["success"], r["sequence"]))
    return rows


def aggregate_failures(observations: list[dict]) -> list[dict]:
    """Count failing steps across failed runs (most frequent failure points)."""
    counts: dict[str, int] = defaultdict(int)
    seqs: dict[str, set] = defaultdict(set)
    for o in observations:
        if o.get("outcome") == "failed" and o.get("failed_step"):
            step = o["failed_step"]
            counts[step] += 1
            seqs[step].add(o.get("template", "?"))
    rows = [
        {"failed_step": step, "failures": n, "templates": ", ".join(sorted(seqs[step]))}
        for step, n in counts.items()
    ]
    rows.sort(key=lambda r: (-cast(int, r["failures"]), cast(str, r["failed_step"])))
    return rows


def aggregate_by_repo(observations: list[dict]) -> dict[str, list[dict]]:
    by_repo: dict[str, list[dict]] = defaultdict(list)
    for o in observations:
        by_repo[o.get("repository", "?")].append(o)
    out: dict[str, list[dict]] = {}
    for repo, runs in by_repo.items():
        out[repo] = aggregate_sequences(runs)
    return out


def table(rows: list[dict], cols: list[tuple[str, str]]) -> str:
    head = "| " + " | ".join(c for _, c in cols) + " |\n"
    sep = "| " + " | ".join("---" for _ in cols) + " |\n"
    body = ""
    for r in rows:
        body += "| " + " | ".join(str(r.get(k, "") if r.get(k) is not None else "—") for k, _ in cols) + " |\n"
    return head + sep + body if rows else "_No data yet._\n"


def write(name: str, title: str, note: str, content: str) -> None:
    VIEWS.mkdir(parents=True, exist_ok=True)
    (VIEWS / name).write_text(
        f"{HEADER}# {title}\n\n{note}\n\n{content}", encoding="utf-8"
    )


def main() -> int:
    observations = load_jsonl(OBSERVATIONS)
    sequences = aggregate_sequences(observations)
    failures = aggregate_failures(observations)
    by_repo = aggregate_by_repo(observations)

    seq_cols = [
        ("sequence", "Sequence"),
        ("frequency", "Runs"),
        ("success", "Success"),
        ("avg_duration_ms", "Avg ms"),
        ("avg_approvals", "Avg approvals"),
        ("templates", "Templates"),
    ]

    # 1. Most reusable sequences (recur often and succeed)
    write(
        "workflow-top-reusable.md",
        "Top reusable workflow sequences",
        "Ranked by frequency, then success rate. Recurrence is descriptive only — "
        "it never promotes a sequence (ADR-007/008).",
        table(sequences, seq_cols),
    )

    # 2. Failure points
    write(
        "workflow-failure-points.md",
        "Workflow failure points",
        "Steps that most often fail across runs — where workflows break.",
        table(failures, [
            ("failed_step", "Failed step"),
            ("failures", "Failures"),
            ("templates", "Templates"),
        ]),
    )

    # 3. By repo
    by_repo_md = ""
    for repo in sorted(by_repo):
        by_repo_md += f"## {repo}\n\n" + table(by_repo[repo], seq_cols) + "\n"
    write(
        "workflow-by-repo.md",
        "Workflow sequences per repo",
        "Grouped by the repository each workflow ran against.",
        by_repo_md.rstrip() + "\n" if by_repo_md else "_No data yet._\n",
    )

    # 4. Proposals — candidates only, never promoted
    candidates = [r for r in sequences if r["frequency"] >= PROPOSAL_MIN_FREQUENCY]
    proposals_note = (
        f"Sequences seen ≥ {PROPOSAL_MIN_FREQUENCY} times — **candidate** reusable "
        "workflows. These are proposals only: promotion requires the scoring "
        "engine and human approval (ADR-007/008). mqobsidian cannot run them."
    )
    write(
        "workflow-proposals.md",
        "Workflow reuse proposals",
        proposals_note,
        table(candidates, seq_cols),
    )

    print(
        f"rendered 4 workflow views from {len(observations)} observations "
        f"({len(sequences)} distinct sequences, {len(candidates)} proposal candidates)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
